### ISSUE TITLE
hey craftify_4.5

### ISSUE THREAD

**Issue by soufianhachimi0** [sid077/craftify_4.5#1]
I dawnload your app from google play [craftify hd wallpaper and auto wallpaper changer] free version 

and your app is crashing  
and ads is not working not showing 

can I have answer 

thank you

**Comment by sid077** [comment]
Sorry for the inconveniences. The app is fixed now there was a backend
issue, you can download the latest version.If crash still happens it would
be great if you can share a screenshot of the the specific part where the
app is crashing.
You can download the latest version here.
https://play.google.com/store/apps/details?id=com.siddhant.craftifywallpapers

Regards,
Siddhant Dubey,
Android developer,
Craftify.

**Comment by soufianhachimi0** [comment]
Ok now app is working 
I wanna use your code source 
How I can fix it on code source 
Where is problem in code source plz

**Comment by sid077** [comment]
It will require your google services file, the one you will get from
firebase and pexel API key
Fixe these two things and you are good to go.

Regards,
Siddhant Dubey,
Android developer,
Craftify

**Comment by soufianhachimi0** [comment]
Ok thank you

**Comment by soufianhachimi0** [comment]
I linkd firebase 
And  I changet pexles APi key
Can you help me for how to upload photo on pexel like your app 

Thank you

**Comment by sid077** [comment]
https://www.pexels.com/api/documentation/
See this to se what more you can do using the api, but i don't think pexels
api support that.
